#!/usr/bin/make
# -*- coding: utf-8 -*-

include etc/base.mk

PROJECT := calc

EXEFILE := 1

INCLUDES := include
INCLUDEL := util/calc/src

LIBS := c_bits c_calls c_fmt c_intrin c_log c_mem c_nexgen32e c_rand \
	c_runtime c_stdio c_str c_stubs c_sysv c_tinymath c_x

3PLIBDIR := 3rdparty
3PLIBS   := compiler_rt gdtoa
